env = Environment(CCFLAGS='-Wall -O3',LIBS='-lrt',CXX = 'mpiCC')
random = Split('../random/mersenne.cpp ../random/random.cc')
main = Glob('../*.cc')
maincc = Glob('../main.cc')[0]
main.remove(maincc)
src = [Glob('*.cc'), main, Glob('../translation/*.cc'), Glob('../xsd/*.cc'), Glob('../handbook/*.cc'), Glob('../matrix/*.cc'), Glob('../externalEnergy/*.cc'), Glob('../internalEnergy/*.cc'), Glob('../simulatedAnnealing/*.cc')] + random
env.Program(target = 'test', source = src)
