env = Environment(CCFLAGS='-Wall -Wno-unknown-pragmas -Wno-format -O3',LIBS='-lrt')
random = Split('../random/mersenne.cpp ../random/random.cc')
tinyxml = Split('../tinyxml/tinyxml.cpp ../tinyxml/tinyxmlparser.cpp ../tinyxml/tinyxmlerror.cpp ../tinyxml/tinystr.cpp')
main = Glob('../*.cc')
maincc = Glob('../main.cc')[0]
main.remove(maincc)
src = [Glob('*.cc'), main, Glob('../translation/*.cc'), Glob('../xsd/*.cc'), Glob('../handbook/*.cc'), Glob('../matrix/*.cc'), Glob('../externalEnergy/*.cc'), Glob('../internalEnergy/*.cc')] + tinyxml + random
env.Program(target = 'test', source = src)
